import {useEffect,useState} from 'react';
import {api} from './api';
import type {Section,User} from './types';
export default function RouteEdit({route,inspectors,onSaved}:{route:Section;inspectors:User[];onSaved:()=>void}){
 const [open,setOpen]=useState(false),[name,setName]=useState(route.name),[notes,setNotes]=useState(route.notes),[inspector,setInspector]=useState(route.inspector_id),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setName(route.name);setNotes(route.notes);setInspector(route.inspector_id);setError('');setOpen(false)},[route.id,route.version]);
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await api.patch(`/routes/${route.id}`,{version:route.version??1,name:name.trim(),notes:notes.trim(),inspector_id:inspector});setOpen(false);onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section>{!open?<button className="button secondary small" disabled={route.state==='in_progress'} onClick={()=>setOpen(true)}>Изменить назначение</button>:<form className="route-edit-form" onSubmit={save}><label className="field">Название<input className="input" value={name} onChange={e=>setName(e.target.value)} required maxLength={200}/></label><label className="field">Инспектор<select className="select" value={inspector} onChange={e=>setInspector(e.target.value)} required>{inspectors.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="field">Примечание<textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></label>{error&&<div className="alert error" role="alert">{error}</div>}<div className="row"><button className="button primary" disabled={busy||!name.trim()}>Сохранить назначение</button><button type="button" className="button secondary" disabled={busy} onClick={()=>setOpen(false)}>Отмена</button></div></form>}{route.state==='in_progress'&&<p className="muted">Изменение доступно после завершения активного осмотра и отправки его очереди.</p>}</section>
}
