import {useCallback,useEffect,useState} from 'react';
import {api} from './api';
import {formatDate} from './components';
import type {User} from './types';
import './team-overview.css';

type Notice={id:string;type:string;title:string;message:string;created_at:string;route_id?:string;defect_id?:string;number?:string};
type ContractorReport={contractor_id:string;name:string;total:number;completed:number;rework:number;overdue:number;average_repair_hours:number|null};
export default function TeamOverview({user,onOpen}:{user:User;onOpen:(notice:Notice)=>void}){
 const [items,setItems]=useState<Notice[]>([]),[reports,setReports]=useState<ContractorReport[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[updated,setUpdated]=useState('');
 const load=useCallback(async()=>{setBusy(true);try{const [notices,rows]=await Promise.all([api.get<Notice[]>('/notifications'),user.role==='dispatcher'?api.get<ContractorReport[]>('/reports/contractors'):Promise.resolve([])]);setItems(notices);setReports(rows);setError('');setUpdated(new Date().toISOString());}catch(e){setError((e as Error).message);}finally{setBusy(false)}},[user.role]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine)void load()},60000);return()=>window.clearInterval(timer)},[load]);
 return <section className="team-overview"><div className="page-head"><div><span className="eyebrow">КОНТРОЛЬ РАБОТ</span><h1>Уведомления и отчёты</h1><p className="muted">Назначения, сдача ремонта и сроки проверки</p></div><button className="button secondary" disabled={busy} onClick={()=>void load()}>{busy?'Обновляем…':'Обновить'}</button></div>{error&&<div role="alert" className="alert error">{error}</div>}{updated&&<p className="muted">Обновлено {formatDate(updated)}</p>}<div className="team-notices">{items.map(item=><button className="card team-notice" key={item.id} onClick={()=>onOpen(item)}><b>{item.title}</b><span>{item.message}</span><small>{formatDate(item.created_at)}{item.number?` · № ${item.number}`:''}</small><em>Открыть →</em></button>)}{!busy&&!items.length&&!error&&<div className="card empty">Нет событий, требующих внимания.</div>}</div>{user.role==='dispatcher'&&<section className="card"><h2>Работа подрядчиков</h2><p className="muted">Текущее состояние назначений. Среднее время рассчитано только по ремонтам с доступной историей.</p><div className="team-report-scroll"><table><thead><tr><th>Подрядчик</th><th>Назначено</th><th>Закрыто</th><th>На доработке</th><th>Просрочено</th><th>Среднее время ремонта</th></tr></thead><tbody>{reports.map(row=><tr key={row.contractor_id}><th>{row.name}</th><td>{row.total}</td><td>{row.completed}</td><td>{row.rework}</td><td>{row.overdue}</td><td>{row.average_repair_hours===null?'Нет данных':`${row.average_repair_hours.toLocaleString('ru-RU',{maximumFractionDigits:1})} ч`}</td></tr>)}</tbody></table></div>{!reports.length&&!busy&&<p className="muted">Подрядчики пока не добавлены.</p>}</section>}</section>
}
